src/Entity/Actus.php
<?php

namespace App\Entity;

use App\Repository\ActusRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActusRepository::class)
 */
class Actus
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="L'adresse mail existe déjà")
 * 
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "E-mail '{{ value }}' n'est pas un e-mail valide."
     * )
     */
    
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     
     */
    private $password;

   
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false,
     *     message="Votre prenom ne peut pas contenir de numéro"
     *)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false,
     *     message="Votre nom ne peut pas contenir de numéro"
     *)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\OneToMany(targetEntity=Orders::class, mappedBy="user")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Customer::class, mappedBy="user", cascade={"remove"})
     */
    private $customers;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->customers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    /**
     * @return Collection|Orders[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Customer[]
     */
    public function getCustomers(): Collection
    {
        return $this->customers;
    }

    public function addCustomer(Customer $customer): self
    {
        if (!$this->customers->contains($customer)) {
            $this->customers[] = $customer;
            $customer->setUser($this);
        }

        return $this;
    }

    public function removeCustomer(Customer $customer): self
    {
        if ($this->customers->removeElement($customer)) {
            // set the owning side to null (unless already changed)
            if ($customer->getUser() === $this) {
                $customer->setUser(null);
            }
        }

        return $this;
    }

    public function __tostring()
    {
        return $this->getlastName() . ' ' . $this->getfirstName() ;
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Form\EditProfileType;
use App\Repository\UserRepository;
use App\Repository\OrdersRepository;
use App\Repository\CommandesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UsersController extends AbstractController
{
    /**
     * @Route("/users", name="users")
     */
    public function index(): Response
    {
        return $this->render('users/user.html.twig');
    }

 /**
     * @Route("/users/modifier", name="users_profil_modifier")
     */
    public function editProfile(Request $request)
    {
        $user = $this->getUser();
        $form = $this->createForm(EditProfileType::class, $user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash(
                'success',
                'Profil mis à jour'
            );
            return $this->redirectToRoute('users');
        }
        
        return $this->render('users/editprofile.html.twig', [
            'form' => $form->createView(),
        ]);
    }

     /**
     * @Route("/users/pass/modifier", name="users_pass_modifier")
     */
    public function editPass(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        if($request->isMethod('POST')){
            $em = $this->getDoctrine()->getManager();

            $user = $this->getUser();

            // On vérifie si les 2 mots de passe sont identiques
            if($request->request->get('pass') == $request->request->get('pass2')){
                $user->setPassword($passwordEncoder->encodePassword($user, $request->request->get('pass')));
                $em->flush();
                $this->addFlash('success', 'Mot de passe mis à jour avec succès');

                return $this->redirectToRoute('users');
            }else{
                $this->addFlash('danger', 'Les deux mots de passe ne sont pas identiques');
            }
        }

        return $this->render('users/editpass.html.twig');
    }

    /**
     * @Route("/users/delete-{id}", name="users_profile_delete")
     */
    public function deleteUser(UserRepository $userRepository, $id)
    {
        $user = $userRepository->find($id);

        $manager = $this->getDoctrine()->getManager();
        $manager->remove($user);
        $manager->flush();

        $this->addFlash(
            'success',
            'Votre profil a bien été supprimé'
        );

        return $this->redirectToRoute('home');
    }

/**
     * @Route("/users/orders", name="users_commandes")
     */
    public function showOrders(OrdersRepository $ordersRepository): Response
    {
        $orders = $ordersRepository->findBySuccessOrders($this->getUser());
        // $orderDetails = [];
     
        return $this->render('users/orders.html.twig', [
            'orders' => $orders
        ]);
    }
     /**
     * @Route("/users/orders/{reference}", name="users_commandes_details")
     */
    public function details($reference, OrdersRepository $ordersRepository): Response
    {
        $order = $ordersRepository->findOneByReference($reference);
        if (!$order || $order->getUser() != $this->getUser() ) {
            return $this->redirectToRoute('users_commandes');
        }

        return $this->render('users/orders_details.html.twig', [
            'reference' => $reference,
            'order' => $order
        ]);
    }





}

templates/users/customer.html.twig
{% extends 'baseUsers.html.twig' %}

{% block title %}Les coordonnées du destinataire
{% endblock %}

{% block body %}
	{{ parent() }}

	<div class="col-10 p-3 shadow">
		<h2 class="p-3 ml-5">Les coordonnées du destinataire</h2>

		<div class="container profile mx-5 ">


			{% for message in app.flashes('success') %}
				<div class="flash-notice alert alert-success w-50">
					{{ message }}
				</div>
			{% endfor %}

			{% if app.user.customers|length  < 1 %}
				<p>Les coordonnées du destinataire non encore enregistrées</p>
			{% else %}

				<!-- // display destinataire -->
				{% for customer in customers %}
					<div class="row ">
						<div class="col-md-8">


							<p>{{ loop.index }}.
								{{customer.firstName}}
								{{customer.lastName}}
							</p>

							<p>&#8470; téléphone:
								{{customer.phone}}</p>

						</div>

						<div class="actions col-md-4">
							<a href="{{path('edit_destinataire', {'id' : customer.id})}}">
								<i class="fa fa-edit p-1  text-dark"></i>
							</a>
							<a href="{{path('delete_destinataire', {'id' : customer.id})}}">
								<i class="fa fa-trash p-1 ml-2 text-dark"></i>
							</a>
						</div>
					</div>
				{% endfor %}
			{% endif %}

			<a href="{{path('add_destinataire')}}" class="btn btn-lg text-center mt-3 ml-3 float-right profile_btn">Ajouter
				            un destinataire
			</a>


		</div>


	</div>


{% endblock %}

templates/users/customerForm.html.twig
{% extends 'baseUsers.html.twig' %}

{% block title %}accueil
{% endblock %}


{% block body %}


	{{ parent() }}
	<div class="col-10 p-3">


		<h2 class="py-3">
			Les coordonnées du destinataire</h2>


		{{form_start(form)}}
		<div class="row">

			<div class="col-md-6">{{form_row(form.first_name, {'label': 'Prenom'} )}}</div>
			<div class="col-md-6">{{form_row(form.last_name, {'label': 'Nom'})}}</div>
			<div class="col-md-6">{{form_row(form.phone, {'label': 'Téléphone'})}}</div>
		</div>
		<button type="submit" id="form-submit" class="btn float-right mb-3">Valider</button>
		{{form_end(form)}}
	</div>

{% endblock %}

templates/users/editpass.html.twig
{% extends 'baseUsers.html.twig' %}

{% block title %}Modification du profil
{% endblock %}

{% block body %}
	{{ parent() }}

	<div class="col-10 p-3">
		<h2 class="py-3">Modification du mot de passe de
			{{app.user.lastName}}
			{{app.user.firstName}}</h2>
		<form method="post">
			<div class="form-field">
				<label for="pass">Mot de passe</label>
				<input type="password" id="pass" name="pass" class="form-control">
			</div>
			<div class="form-field">
				<label for="pass2">Confirmer le mot de passe</label>
				<input type="password" id="pass2" name="pass2" class="form-control">
			</div>
			<button type="submit" class="btn btn-lg text-center mt-3 ml-3 float-right profile_btn">Valider</button>

		</form>
	</div>

{% endblock %}

templates/users/editprofile.html.twig
{% extends 'baseUsers.html.twig' %}

{% block title %}Modification du profil
{% endblock %}

{% block body %}
	{{ parent() }}

	<div class="col-10 p-3">
		<h2 class="py-3">Modification du profil de
			{{app.user.lastName}}
			{{app.user.firstName}}</h2>
		{{ form(form) }}
		</div>

	{% endblock %}

templates/users/orders.html.twig
{% extends 'baseUsers.html.twig' %}

{% block title %}Mes commandes
{% endblock %}

{% block body %}
	{{ parent() }}

	<div class="col-10 p-3 shadow">
		<h2 class="p-3 ml-5">Mes commandes</h2>

		<div class="container-fluid profile mx-5">


			{% for message in app.flashes('success') %}
				<div class="flash-notice alert alert-success w-50">
					{{ message }}
				</div>
			{% endfor %}

			{% if orders|length  < 1 %}

				<div class="col-12 text-center">
					<p>Pas encore de commandes
					</p>
				</div>
			{% else %}

				<!-- // display addresses -->
				<div class="row">
					{% for order in orders %}
						<div class="col-lg-3 col-md-12 border m-2 p-3 myorder">

							<h4>Ref:
								{{order.reference}}</h4>
							<p>{{order.createdAt|date('Y-m-d H:i') }}</p>
							<p>Prix total:
								{{order.total}}
								€
							</p>
							{% if order.state == 1 %}
								<p class="badge badge-primary p-1">Payée</p>
							{% elseif order.state == 2 %}
								<p class="badge badge-warning p-1">Préparation en cours</p>
							{% elseif order.state == 3 %}
								<p class="badge badge-success  p-1">Prêt pour la collecte</p>
							{% elseif order.state == 4 %}
								<p class="badge badge-secondary p-1">Récupéré</p>
							{% endif %}
							<hr>
							<p>
								<a href="{{path('users_commandes_details', {'reference' : order.reference})}}">
									<i class="fas fa-plus"></i>
									Details</a>
							</p>


						</div>
					{% endfor %}
				</div>

			{% endif %}


		</div>


	</div>

{% endblock %}

templates/users/orders_details.html.twig
{% extends 'baseUsers.html.twig' %}

{% block title %}Mes commandes
{% endblock %}

{% block body %}
	{{ parent() }}

	<div class="col-10 p-3 shadow">
		<h2 class="p-3 ml-5">Commande &#x2116;  :
			{{order.reference}}
		</h2>


		<div class="container mx-5">

			<p>Date de commande:
				{{order.createdAt|date('Y-m-d H:i') }}</p>
			{# <h4>{{order.delivery|raw}}</h4> #}
			<p>Destinataire:
				{{order.customer|raw}}</p>
			<p>
				Statut de la commande :
				{% if order.state == 1 %}
					<span class="badge badge-primary p-1">Payée</span>
				{% elseif order.state == 2 %}
					<span class="badge badge-warning p-1">Préparation en cours</span>
				{% elseif order.state == 3 %}
					<span class="badge badge-success p-1">Prêt pour la collecte</span>
				{% elseif order.state == 4 %}
					<span class="badge badge-secondary p-1">Récupéré</span>
				{% endif %}
			</p>


			<table class="table table-responsive">
				<thead class="text-center">
					<tr>
						<th>N</th>
						<th>Menu</th>
						<th>Prix</th>
						<th>Quantité</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for item in order.orderDetails %}
						<tr>
							<td>{{ loop.index }}.</td>
							<td>{{ item.menu }}</td>
							<td>{{ item.price }}&euro;</td>
							<td class="text-center">{{ item.quantity }}</td>
							<td>
								{{ item.price * item.quantity }}&euro;</td>
						</tr>
					{% endfor %}
				</tbody>
				<tfoot>
					<tr>
						<td colspan="4" class="text-right">
							<strong>Total :
							</strong>
						</td>
						<td>{{ order.total }}&euro;</td>
					</tr>
				</tfoot>
			</table>


		</div>
	</div>


{% endblock %}

templates/users/user.html.twig
{% extends 'baseUsers.html.twig' %}

{% block title %}accueil
{% endblock %}


{% block body %}


	{{ parent() }}


	<div class="col-10 p-3 shadow">

		<h2 class="p-3 ml-5">Profile de
			{{app.user.lastName}}
			{{app.user.firstName}}</h2>

		<div class="container-fluid profile mx-5">

			<div class="row ">

				<div class="col-3">Nom:
				</div>
				<div class="col-9">
					{{app.user.lastName}}</div>
			</div>
			<div class="row">
				<div class="col-3">
					Prenom:
				</div>
				<div class="col-9">
					{{app.user.firstName}}
				</div>
			</div>
			<div class="row">
				<div class="col-3">
					Email:
				</div>
				<div class="col-9">
					{{app.user.email}}
				</div>
			</div>
			<div class="row">
				<div class="col-3">
					Telephone:
				</div>
				<div class="col-9">
					{{app.user.phone}}
				</div>
			</div>


			<div class="row pt-3">
				<div class="col-8"></div>
			</div>
			<div class="row pt-3">
				<div class="col-8">
					<div>
						<a href="{{ path('users_pass_modifier')}}" class="btn btn-lg text-center mt-3 ml-3 float-left profile_btn">Mot de passe
							<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
								<path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
							</svg>
						</a>
					</div>
					<div>
						<a href="{{ path('users_profil_modifier') }}" class="btn btn-lg text-center mt-3 ml-3 float-left profile_btn">Profile
							<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
								<path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
							</svg>
						</a>
					</div>
					<div>
						<a href="{{ path('users_profile_delete', {'id':app.user.id})}}" class="btn btn-lg text-center mt-3 ml-3 float-left profile_btn">Profile
							<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
								<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
							</svg>
						</a>
					</div>
				</div>
			</div>
		</div>


	</div>


{% endblock %}